### ISSUE TITLE
React Native 0.66

### ISSUE THREAD

**Issue by acrabb** [BunHouth/react-native-progress-hud#1]
Is anyone else having issues running Android with React Native 0.66+ ?
I just upgraded and now Android Studio is spitting out this progress-hud error:

```
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.kaopiz:kprogresshud:1.2.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/kaopiz/kprogresshud/1.2.0/kprogresshud-1.2.0.pom
       - file:/APPREPO/node_modules/react-native/android/com/kaopiz/kprogresshud/1.2.0/kprogresshud-1.2.0.pom
       - file:/APPREPO/node_modules/jsc-android/dist/com/kaopiz/kprogresshud/1.2.0/kprogresshud-1.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/kaopiz/kprogresshud/1.2.0/kprogresshud-1.2.0.pom
       - https://www.jitpack.io/com/kaopiz/kprogresshud/1.2.0/kprogresshud-1.2.0.pom
     Required by:
         project :app > project :progress-hud

```

I've tried re-installing, restarting everything, updating Android Studio, etc.
No luck.
Any ideas?

**Comment by acrabb** [comment]
UPDATE:
To upgrade, I followed this diff: https://react-native-community.github.io/upgrade-helper/?from=0.64.1&to=0.66.1
...which replaces the jcenter repositories with mavenCentral

Adding back in jcenter fixes the build.

Can progress-hud be added to mavenCentral?

**Comment by BunHouth** [comment]
Thanks @acrabb, I'll do an update today after get more free time.

**Comment by BunHouth** [comment]
Please update package to `1.3.0`
https://www.npmjs.com/package/progress-hud
